# Generated by Django 4.2.1 on 2023-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
