# Generated by Django 4.2.1 on 2023-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_post_content_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image1_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image2_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image3_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
